### ISSUE TITLE
Alarm is disarmed if in "armed_home" a new device was detected

### ISSUE THREAD

**Issue by vpomax** [runningman84/home-assistant-apps#11] opened 2019-10-29 00:25 UTC
If the alarmsystem is in the state "armed_home" and a new device in "device_trackers" is detected (e.g. I active BT or wifi of my android phone)... system change the status in "disarmed".
This don't have to happens whem alarmsystem is "armed_home" but only in "armed_away".

**Comment by runningman84** [comment] 2019-10-29 08:10
I am not sure if I get you... The system should automatically disarm in case you come home. It should also automatically arm at night if all trackers are at home. It should also arm away once all trackers are not home.

**Comment by vpomax** [comment] 2019-10-29 08:58
I discovered that my wife Huawei P20 lite sometimes diconnect and after few minutes reconnect again to wifi.
This causes continuous "armed_home" and "disarmed" of the system. I tried using an android app that keeps the wifi of the Huawei always connected, but it doesn't always work. Temporary I removed her wifi phone by device_tracker section, until I will find a solution.

**Comment by andyinno** [comment] 2019-11-28 17:34
@vpomax try the updated version of the file. What you are describing is exactly the same that I reported in #10

**Comment by runningman84** [comment] 2020-01-02 21:33
I think this is a duplicate of #10

**Closed as completed by runningman84** 2020-01-02 21:33 UTC
